version: '3.3'
services:
  web:
    image: danielprog/avito-phpapache:v1
    container_name: php73
    depends_on: 
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: mysql8
    image: danielprog/avito-mysql:v1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
